### ISSUE TITLE
Cookbook upload errors

### ISSUE THREAD

**Issue by jhmartin** [Lytro/aws_developer_tools#11]
When attempting to upload into a chef-11 server using ruby 1.9.3 and knife 11.8:

FATAL: Cookbook file spec/spec_helper.rb has a ruby syntax error:
FATAL: /Users/jhmartin/.librarian/tmp/chef/integration/knife/install/f4006e0d82b6db7d5bb310b4c9374d32/aws_developer_tools/spec/spec_helper.rb:9: syntax error, unexpected ':', expecting ')'
FATAL: ...:ChefRunner.new(cookbook_path: cookbook_paths, platform: 'ub...
FATAL:                               ^
FATAL: /Users/jhmartin/.librarian/tmp/chef/integration/knife/install/f4006e0d82b6db7d5bb310b4c9374d32/aws_developer_tools/spec/spec_helper.rb:9: syntax error, unexpected ':', expecting '='
FATAL: ...ath: cookbook_paths, platform: 'ubuntu', version: '10.04') d...
FATAL:                               ^
FATAL: /Users/jhmartin/.librarian/tmp/chef/integration/knife/install/f4006e0d82b6db7d5bb310b4c9374d32/aws_developer_tools/spec/spec_helper.rb:9: syntax error, unexpected ',', expecting kEND
FATAL: ...ook_paths, platform: 'ubuntu', version: '10.04') do |node|
FATAL:                               ^
FATAL: /Users/jhmartin/.librarian/tmp/chef/integration/knife/install/f4006e0d82b6db7d5bb310b4c9374d32/aws_developer_tools/spec/spec_helper.rb:9: syntax error, unexpected ')', expecting kEND
FATAL: ...m: 'ubuntu', version: '10.04') do |node|
FATAL:                               ^
FATAL: /Users/jhmartin/.librarian/tmp/chef/integration/knife/install/f4006e0d82b6db7d5bb310b4c9374d32/aws_developer_tools/spec/spec_helper.rb:19: syntax error, unexpected kEND, expecting $end

**Comment by jhmartin** [comment]
Not sure what I did but its working now, closing.

**Comment by anujbiyani** [comment]
:+1:
